# Generated by Django 3.1.7 on 2023-01-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=200, null=True)),
                ('cover_iamge', models.CharField(max_length=1000, null=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('wolt_profile', models.CharField(max_length=200, null=True)),
                ('fodoora_profile', models.CharField(max_length=200, null=True)),
                ('trip_advisor', models.CharField(max_length=200, null=True)),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('rank', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
    ]
