# Generated by Django 3.1.7 on 2023-01-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rank',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Kitchen_type',
            field=models.ManyToManyField(null=True, to='core.KitchenType'),
        ),
    ]
