# Generated by Django 3.1.7 on 2023-01-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230103_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Kitchen_type',
            field=models.ManyToManyField(null=True, related_name='kitchentype', to='core.KitchenType'),
        ),
    ]
