# Generated by Django 3.1.7 on 2023-01-03 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230103_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Kitchen_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Kitchen_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchentype', to='core.kitchentype'),
        ),
    ]
