# Generated by Django 3.1.7 on 2023-01-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230103_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Kitchen_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Kitchen_type',
            field=models.ManyToManyField(null=True, related_name='kitchentype', to='core.KitchenType'),
        ),
    ]
