# Generated by Django 3.1.7 on 2023-01-03 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_resturantreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturantreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
