# Generated by Django 3.1.7 on 2023-01-09 23:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20230103_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.CharField(max_length=500, null=True)),
                ('desc', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCatgory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.CharField(max_length=500, null=True)),
                ('desc', models.CharField(max_length=500)),
                ('activ', models.BooleanField(default=True)),
                ('resturant_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rank', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('image', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=225)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_vegan', models.BooleanField(default=False, null=True)),
                ('is_vigetar', models.BooleanField(default=False, null=True)),
                ('is_halal', models.BooleanField(default=False, null=True)),
                ('contains_pork', models.BooleanField(default=False, null=True)),
                ('gluten_free', models.BooleanField(default=False, null=True)),
                ('can_be_gluten_free', models.BooleanField(default=False, null=True)),
                ('organic', models.BooleanField(default=False, null=True)),
                ('activ', models.BooleanField(default=True)),
                ('kitchen_type', models.ManyToManyField(to='core.KitchenType')),
                ('resturant_menu_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menucatgory')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resturantreview',
            name='review_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activ', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('percentage', models.PositiveSmallIntegerField()),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('ofer_start', models.DateTimeField()),
                ('ofer_end', models.DateTimeField()),
                ('activ', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='resturant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('activ', models.BooleanField(default=True)),
                ('food', models.ManyToManyField(to='core.Product')),
            ],
        ),
    ]
