# Generated by Django 3.1.7 on 2023-01-09 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230109_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerunit',
            name='Offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.offer'),
        ),
    ]
