# Generated by Django 3.1.7 on 2023-01-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_offerunit_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucatgory',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
