# Generated by Django 3.1.7 on 2023-01-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_menucatgory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='number_of_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
