# Generated by Django 3.1.7 on 2023-01-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230112_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
