# Generated by Django 3.1.7 on 2023-01-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230112_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucatgory',
            name='resturant_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_catagories', to='core.menu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resturant_menu_catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core.menucatgory'),
        ),
    ]
