# Generated by Django 3.1.7 on 2023-02-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230213_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='avatar',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
