# Generated by Django 3.1.7 on 2023-02-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230214_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='booking',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
